
# action labels
action_clear_filters: Clear Filters
action_copied: Copied!
action_copy: Copy
action_hide: Code
action_isolate: Isolate
action_reset: Reset
action_show: Code
action_shutter: Close
action_update: Render

# general labels
label_accept_values: "Accepts:"
label_access: Access
label_components: Components
label_content: Content
label_default_value: "Default:"
label_deprecated: Deprecated
label_description: Description
label_documents: Documents
label_error: "ERROR:"
label_filters: Filters
label_logo: Project Logo
label_props: Props
label_static: Site Links
label_sanctioned: Sanctioned
label_sections: Sections
label_tags: Tags
label_toc: Page Contents

# page names
page_catalog_title: Asset Index
page_error_title: Error
page_home_title: Homepage
page_isolate_title: CoBE Isolation

# messages/alerts
msg_asset_count: Showing {count} of {total} assets in docsite.
msg_copied: Copied to Clipboard!
msg_filter_name: filter by name
msg_goto_page: Go to {title} page.
msg_no_component_description: No comments were found for this component.
msg_no_prop_description: No comments were found for this component property.
msg_scrollto: Scroll to {name}.
