
# action labels
action-clear-filters: Clear Filters
action-copied: Copied!
action-copy: Copy
action-filter-name: filter by name
action-hide: Code
action-reset: Reset
action-show: Code
action-update: Render

# general labels
label-accept-values: "Accepts:"
label-components: Components
label-default-value: "Default:"
label-deprecated: DEPRECATED
label-description: Description
label-documents: Documents
label-error: "ERROR:"
label-filters: Filters
label-logo: Project Logo
label-primary: Site
label-props: Props
label-sections: Sections
label-tags: Tags
label-toc: Table of Contents

# page names
page-home-title: "{title}"
page-index-title: Asset Index

# messages/alerts
msg-asset-count: "{count} of {total} assets listed."
msg-copied: Copied to Clipboard!
msg-no-comments: No comments were found for this {item}.
