
# action labels
action_clear_filters: Clear Filters
action_copied: Copied!
action_copy: Copy
action_hide: Code
action_reset: Reset
action_show: Code
action_update: Render

# general labels
label_accept_values: "Accepts:"
label_components: Components
label_default_value: "Default:"
label_deprecated: Deprecated
label_description: Description
label_documents: Documents
label_error: "ERROR:"
label_filters: Filters
label_logo: Project Logo
label_primary: Site
label_props: Props
label_sanctioned: Sanctioned
label_sections: Sections
label_tags: Tags
label_toc: Table of Contents

# page names
page_catalog_title: Asset Index
page_home_title: Homepage

# messages/alerts
msg_asset_count: Showing {count} of {total} assets in docsite.
msg_copied: Copied to Clipboard!
msg_filter_name: filter by name
msg_goto_page: Go to {title} page.
msg_no_component_description: No comments were found for this component.
msg_no_prop_description: No comments were found for this component property.
msg_scrollto: Scroll to {name}.
