import packson from '#packson' with { type: 'json' }


let dtf = new Intl.DateTimeFormat("en-GB", 
{
    weekday: "long",
    month: 'long',
    day: "numeric",
    year: "numeric",
    hour: 'numeric',
    hour12: false,
    minute: 'numeric',
    second: 'numeric',
    timeZone: "UTC",
    timeZoneName: 'short'
});

export default function (title)
{
    let banner =
    `
    /*
        ${title} documentation site bundle.
        
        Generated by ${packson.title} ver. ${packson.version}
        on ${dtf.format(new Date())}

        ${packson.title} software is released under the ${packson.license} License. 
    */
    `;

    return banner;
}
